/**:
  ros__parameters:
    address: 0.0.0.0
    port: 8765
    send_buffer_limit: 10000000
    min_qos_depth: 1
    max_qos_depth: 5
    use_compression: true
    num_threads: 4
    topic_whitelist:
      - ^/odomimu$
      - ^/poseimu$
      - ^/pathimu$
      - ^/imu$
      - ^/tf$
      - ^/tf_static$
      - ^/points_msckf$
      - ^/loop_feats$
      - ^/trackhist_compressed$
      - ^/camera/camera/infra1/image_rect_raw$
      - ^/camera/camera/infra1/camera_info$
      - ^/camera/camera/infra2/image_rect_raw$
      - ^/camera/camera/infra2/camera_info$
      - ^/system/cpu_usage$
      - ^/system/cpu_per_core$
      - ^/system/cpu_freq_big$
      - ^/system/cpu_freq_little$
      - ^/system/mem_usage$
      - ^/system/cpu_temp$
      - ^/system/load_avg$
      - ^/rosout$
      - ^/vio/drift_distance$
      - ^/vio/drift_xy$
      - ^/vio/drift_z$
      - ^/vio/velocity_norm$
